version: '3'
services:
  app-server:
    image: nielinjie/quickqui-app-server:latest
    ports:
      - "4000:4000"
  front:
    image: nielinjie/quickqui-front:latest
    depends_on:
      - app-server
      - model-server
    links:
      - model-server
      - app-server
    ports:
      - "3000:3000"
    environment:
      - ENV=dev_docker