version: '3'
services:
  plantuml-service:
    image: bitjourney/plantuml-service:1.3.5
    ports:
      - "1608:1608"
    restart: always
  model-front:
    image: nielinjie/quickqui-model-front:latest
    depends_on:
      - model-server
    links:
      - model-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
  model-server:
    image: nielinjie/quickqui-model-server:latest
    depends_on:
      - plantuml-service
    links:
      - plantuml-service
    environment:
      - ENV=dev_docker
    volumes:
      - ./:/modelProjectDir

